
dist: focal

arch:
  - amd64

services:
  - docker

os: linux

language: php

php:
  - 8.0

env:
  - SDK=Android
  - SDK=CLI
  - SDK=Dart
  - SDK=Deno
  - SDK=Flutter
  - SDK=Kotlin
  - SDK=Node
  - SDK=PHP
  - SDK=Python
  - SDK=Ruby
  - SDK=SwiftClient
  - SDK=SwiftServer
  - SDK=Web

notifications:
  email:
    - team@appwrite.io

before_install:
  - >
    if [ ! -z "${DOCKERHUB_PULL_USERNAME:-}" ]; then
      echo "${DOCKERHUB_PULL_PASSWORD}" | docker login --username "${DOCKERHUB_PULL_USERNAME}" --password-stdin
    fi


install:
  - docker --version
  - composer install

script:
  - vendor/bin/phpunit tests/${SDK}Test.php