language: php

php:
  - 7.4

notifications:
  email:
    - team@appwrite.io

install:
  - echo 'DOCKER_OPTS="$DOCKER_OPTS --registry-mirror=https://mirror.gcr.io"'
  - composer install

script:
  - vendor/bin/phpunit
