language: php

php:
  - 7.4

notifications:
  email:
    - team@appwrite.io

install:
  - echo "${DOCKERHUB_PULL_PASSWORD}" | docker login --username "${DOCKERHUB_PULL_USERNAME}" --password-stdin
  - composer install

script:
  - vendor/bin/phpunit
