dist: xenial

language: php

php:
  - 7.3

notifications:
  email:
    - team@appwrite.io

before_script: composer install

install:
  - >
      echo "80\n443\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n" | docker run -it --rm \
          --volume /var/run/docker.sock:/var/run/docker.sock \
          --volume "$(pwd)"/appwrite:/install/appwrite:rw \
          -e version=0.6.2 \
          appwrite/install
  - sleep 20

script:
  - vendor/bin/phpunit
